version: "3.7"
services:
  product-validation-api:
    build: 
      context: .
      dockerfile: "src/ProductValidation.API/Dockerfile"
    ports:
      - "8000:80"
    depends_on:
      - product-validation-db
  product-validation-db:
    build:
      context: build/db
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "8001:1433"