// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductValidation.Core.Repository;

#nullable disable

namespace ProductValidation.API.Migrations
{
    [DbContext(typeof(ProductValidationContext))]
    [Migration("20220711210603_BarcodeLengthSeeding")]
    partial class BarcodeLengthSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductValidation.Core.Models.BannedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BannedWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "nike",
                            Value = "adidas"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "nike",
                            Value = "under armour"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "nike",
                            Value = "underarmour"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "adidas",
                            Value = "nike"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "adidas",
                            Value = "puma"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "apple",
                            Value = "google"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "apple",
                            Value = "microsoft"
                        });
                });

            modelBuilder.Entity("ProductValidation.Core.Models.BarcodeLength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BarcodeLengths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "nike",
                            Value = 12
                        },
                        new
                        {
                            Id = 2,
                            Brand = "adidas",
                            Value = 15
                        },
                        new
                        {
                            Id = 3,
                            Brand = "apple",
                            Value = 8
                        });
                });

            modelBuilder.Entity("ProductValidation.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
